# Generated by Django 4.1 on 2022-09-23 17:53

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="function",
            name="summary",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="summary",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="parameters",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. \
                    A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
    ]
