# Generated by Django 4.1 on 2022-09-22 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("builder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="build",
            name="environment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.environment"
            ),
        ),
        migrations.AddField(
            model_name="build",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.package",
            ),
        ),
        migrations.AddIndex(
            model_name="build",
            index=models.Index(
                fields=["status", "created_at"], name="build_status_created_at"
            ),
        ),
        migrations.AddIndex(
            model_name="build",
            index=models.Index(
                fields=["status", "updated_at"], name="build_status_updated_at"
            ),
        ),
    ]
