version: "3.5"

x-environment: &environment
  PYTHONDONTWRITEBYTECODE: 1
  PYTHONUNBUFFERED: 1
  PYTHONBREAKPOINT: remote_pdb.set_trace
  REMOTE_PDB_HOST: 0.0.0.0

services:
  runner:
    image: plugin_runner:latest
    container_name: runner
    environment:
      <<: *environment
      REMOTE_PDB_PORT: 3333
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: bugsbunny
      RABBITMQ_PASSWORD: wascallywabbit
    ports:
      - 3333:3333
    networks:
      - proto-network
    volumes:
      - $PROJECT_HOME/bgproto/runner:/opt/runner/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rabbitmq
      - redis
      - registry
  worker:
    image: plugin_runner:latest
    command: worker
    container_name: worker
    environment:
      <<: *environment
      REMOTE_PDB_PORT: 4444
      REGISTRY: "localhost:5000"
    ports:
      - 4444:4444
    networks:
      - proto-network
    volumes:
      - $PROJECT_HOME/bgproto/runner:/opt/runner/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: bugsbunny
      RABBITMQ_DEFAULT_PASS: wascallywabbit
    networks:
      - proto-network
    ports:
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    volumes:
      - rabbitmq-home:/var/lib/rabbitmq
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - proto-network
    ports:
      - 6379:6379
  registry:
    image: registry:2
    container_name: registry
    networks:
      - proto-network
    ports:
      - 5000:5000

networks:
  proto-network:
    driver: bridge
    name: proto-network

volumes:
  rabbitmq-home:
