version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-bugs}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULTPASS:-wascallywabbit}
    networks:
      - proto-network
    ports:
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - proto-network
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  registry:
    image: registry:2
    container_name: registry
    networks:
      - proto-network
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry

networks:
  proto-network:
    driver: bridge
    name: proto-network

volumes:
  rabbitmq-data:
  redis-data:
  registry-data:
