name: Tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [cli, functionary]
    name: ${{ matrix.component }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        with:
          path: ~/.cache.pip
          key:
            ${{ runner.os }}-pip-${{ hashFiles(format('{0}/requirements*.txt',
            matrix.component)) }}
      - name: pip install
        run:
          python -m pip install -r ${{ matrix.component }}/requirements.txt -r
          ${{ matrix.component }}/requirements-dev.txt
      - name: run tests
        run: pytest ${{ matrix.component }}/
